# Generated by Django 3.0.6 on 2020-05-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copas', '0002_auto_20200509_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabecera',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cabecera',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
