# Generated by Django 3.0.6 on 2020-05-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copas', '0003_auto_20200509_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='copa',
            name='slug',
            field=models.SlugField(default='default', max_length=100),
            preserve_default=False,
        ),
    ]
