# Generated by Django 3.0.6 on 2020-05-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copas', '0004_auto_20200510_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabecera',
            name='overlay',
            field=models.BooleanField(default=False),
        ),
    ]
