# Generated by Django 3.0.6 on 2020-05-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copas', '0005_cabecera_overlay'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='overlay',
            field=models.BooleanField(default=False),
        ),
    ]
